### ISSUE TITLE
Unable to close tutorial

### ISSUE THREAD

**Issue by Stephen-Gates** [datahq/data-desktop#22]
After opening tutorial from app, there is no way to close it 

<img width="911" alt="screenshot 2017-12-04 19 44 13" src="https://user-images.githubusercontent.com/9379524/33546129-ef173544-d92b-11e7-9945-f17891062542.png">

Add close button to Window

**Comment by Mikanebu** [comment]
@Stephen-Gates Thanks for reporting this. We will take into consideration.

**Comment by anuveyatsu** [comment]
@Stephen-Gates I think you're using an old version of the app (and it is not updated because auto-update feature was added later). Can you please use this version - https://github.com/datahq/data-desktop/releases/tag/v0.4.1 which should work?

**Comment by Stephen-Gates** [comment]
Fixed - old version :-(
