### ISSUE TITLE
On drag .csv to app, allow edit of field format and description

### ISSUE THREAD

**Issue by Stephen-Gates** [datahq/data-desktop#23]
It's great that the name and title of the data can be editing and the field type as well.

Feature request to allow editing of field format and description

<img width="932" alt="screenshot 2017-12-04 19 50 43" src="https://user-images.githubusercontent.com/9379524/33546737-8c9fb150-d92d-11e7-9260-61c1f116253c.png">

**Comment by anuveyatsu** [comment]
@Stephen-Gates It is editable - you need to press "Edit" button so it is in edit mode. Please, hit me back if it doesn't help.

**Comment by Stephen-Gates** [comment]
@anuveyatsu you're correct.

When I looked at the UI:


- I saw the drop down box for `type` and assumed you could directly edit - you can't.
- I saw no drop down box for `format` and assumed you couldn't edit - you can

<img width="899" alt="screenshot 2017-12-05 05 50 47" src="https://user-images.githubusercontent.com/9379524/33573118-a42daf22-d980-11e7-8a19-bb1ca39edceb.png">

Why not have a drop down for `format` because right know I can type in rubbish and it is accepted.

<img width="324" alt="screenshot 2017-12-05 05 54 50" src="https://user-images.githubusercontent.com/9379524/33573208-e35f2ed2-d980-11e7-86e7-acb374f75338.png">

Also the user interface does not support some elements of `type` & `format` like:
- pattern in [`date`](https://frictionlessdata.io/specs/table-schema/#date)/`time`/`datetime`
- lexical formatting in [`number`](https://frictionlessdata.io/specs/table-schema/#number)

I assume to support these features you would have to upload a `datapackage.json`?

**Comment by anuveyatsu** [comment]
@Stephen-Gates I agree that "Format" should also be a drop-down so it'd clear that both "Type" and "Format" can be edited.

Not sure why do you think `date`/`time`/`datetime` are not supported? You can select them from the drop-down for "Type" + you can have lexical formatting in the "Format" section. Probably you mean that auto-generated schema does not identify it?

**Comment by Stephen-Gates** [comment]
@anuveyatsu again you are correct.

<img width="868" alt="screenshot 2017-12-05 21 35 56" src="https://user-images.githubusercontent.com/9379524/33605194-5f0fe89a-da04-11e7-9c78-9b8fdc831159.png">

**Comment by anuveyatsu** [comment]
@Stephen-Gates we'll fix having drop-downs for "format" property in this issue https://github.com/datahq/data-desktop/issues/26
